"""Camada de persistência do totem.

Usa SQLite (stdlib) para armazenar **produtos**, **movimentações de estoque**
e **vendas** realizadas no totem. O catálogo é sincronizado a partir da
**Wake Commerce**; o estoque operacional é gerido no painel administrativo.

Os símbolos públicos são reexportados aqui para manter ``from database import ...``.

Esquema (resumo)
----------------

- ``products`` — catálogo (sku, preço, categoria, imagem, estoque, mínimo, ativo).
- ``stock_movements`` — variações de estoque (entrada, saída, venda, ajuste, inicial).
- ``transactions`` / ``transaction_items`` — pedidos e itens com snapshot.
- ``sellers`` — credenciais dos vendedores.
- ``events`` / ``event_products`` / ``event_sellers`` — inventário por evento.

Invariante: toda alteração de ``products.stock`` é feita na mesma conexão
que insere a ``stock_movements`` correspondente.
"""
from __future__ import annotations

from .promotions import (
    RULE_TYPE_LABELS,
    active_promotion_tooltip_by_product_id,
    build_promo_display_map,
    create_promotion,
    delete_promotion,
    enrich_product_with_promo,
    get_active_promotions_for_event,
    get_promotion,
    list_promotions_for_event,
    product_ids_with_active_promotions_for_event,
    toggle_promotion_active,
    update_promotion,
)
from .badges import (
    event_badge_fg_hex,
    event_badge_style_pairs,
    normalize_event_badge_color,
)
from .connection import DB_PATH, get_conn
from .events import (
    EXPORT_MOVEMENTS_CSV_CAP,
    EXPORT_SALES_ITEMS_CSV_CAP,
    EXPORT_SALES_SUMMARY_CSV_CAP,
    add_product_to_event,
    add_seller_to_event,
    archive_event,
    count_event_products_filtered,
    create_event,
    delete_event,
    find_product_by_sku_or_id,
    get_event_financial_report,
    get_active_event_for_seller,
    get_event,
    get_event_sales_dashboard,
    get_event_stats,
    get_event_stock_stats,
    get_seller_admin_event_selection_id,
    list_active_event_product_stocks,
    list_event_products,
    list_event_products_filtered_for_client,
    list_event_products_for_client,
    list_event_products_slice,
    list_event_sellers,
    list_events,
    list_transaction_items_for_event_period,
    list_transactions_summary_for_event_period,
    remove_product_from_event,
    replace_seller_event_assignment,
    restore_event,
    update_event,
    update_event_product_stock,
)
from .event_stock import (
    list_event_stock_movements,
    register_event_stock_adjustment,
    register_event_stock_entry,
    register_event_stock_exit,
)
from .products import (
    count_products_admin_filtered,
    get_product,
    get_product_in_event,
    list_active_product_stocks,
    list_distinct_product_categories,
    list_products_admin,
    list_products_admin_slice,
    list_products_for_client,
    set_product_active,
    sync_products_from_wake,
    update_product_min_stock,
    upsert_wake_variant,
)
from .schema import init_db
from .sellers import (
    create_seller_account,
    delete_seller,
    ensure_seller_account,
    get_seller,
    get_seller_by_email,
    list_seller_pin_hashes,
    list_sellers,
    update_seller_account,
    update_seller_last_login,
)
from .stock import (
    count_stock_movements,
    get_product_events_stock_total,
    get_products_library_stats,
    get_stock_stats,
    list_stock_movements,
    max_stock_movement_id_filtered,
    register_stock_adjustment,
    register_stock_entry,
    register_stock_exit,
)
from .transactions import (
    cancel_pending_transaction_for_seller,
    confirm_transaction_with_aut,
    count_transactions_for_event,
    count_transactions_for_seller,
    create_transaction,
    generate_order_number,
    get_pending_transaction_if_owned,
    get_pending_transaction_restore_payload,
    get_stats,
    get_transaction,
    get_transaction_by_order_number,
    list_transactions,
    list_transactions_for_event,
    list_transactions_for_seller,
    refund_transaction,
    reset_totem_to_default_state,
    update_pending_transaction,
)

__all__ = [
    "RULE_TYPE_LABELS",
    "active_promotion_tooltip_by_product_id",
    "build_promo_display_map",
    "create_promotion",
    "delete_promotion",
    "enrich_product_with_promo",
    "get_active_promotions_for_event",
    "get_promotion",
    "list_promotions_for_event",
    "product_ids_with_active_promotions_for_event",
    "toggle_promotion_active",
    "update_promotion",
    "EXPORT_MOVEMENTS_CSV_CAP",
    "EXPORT_SALES_ITEMS_CSV_CAP",
    "EXPORT_SALES_SUMMARY_CSV_CAP",
    "DB_PATH",
    "add_product_to_event",
    "add_seller_to_event",
    "archive_event",
    "cancel_pending_transaction_for_seller",
    "confirm_transaction_with_aut",
    "count_event_products_filtered",
    "count_products_admin_filtered",
    "count_stock_movements",
    "count_transactions_for_event",
    "count_transactions_for_seller",
    "create_event",
    "delete_event",
    "get_event_financial_report",
    "create_seller_account",
    "create_transaction",
    "delete_seller",
    "ensure_seller_account",
    "event_badge_fg_hex",
    "event_badge_style_pairs",
    "find_product_by_sku_or_id",
    "generate_order_number",
    "get_active_event_for_seller",
    "get_conn",
    "get_event",
    "get_event_sales_dashboard",
    "get_event_stats",
    "get_event_stock_stats",
    "get_pending_transaction_if_owned",
    "get_pending_transaction_restore_payload",
    "get_product",
    "get_product_events_stock_total",
    "get_product_in_event",
    "get_products_library_stats",
    "get_seller",
    "get_seller_admin_event_selection_id",
    "get_seller_by_email",
    "get_stats",
    "get_stock_stats",
    "get_transaction",
    "get_transaction_by_order_number",
    "init_db",
    "list_active_event_product_stocks",
    "list_active_product_stocks",
    "list_distinct_product_categories",
    "list_event_products",
    "list_event_products_filtered_for_client",
    "list_event_products_for_client",
    "list_event_products_slice",
    "list_event_sellers",
    "list_event_stock_movements",
    "list_events",
    "list_products_admin",
    "list_products_admin_slice",
    "list_products_for_client",
    "list_seller_pin_hashes",
    "list_sellers",
    "list_stock_movements",
    "list_transaction_items_for_event_period",
    "list_transactions",
    "list_transactions_for_event",
    "list_transactions_for_seller",
    "list_transactions_summary_for_event_period",
    "max_stock_movement_id_filtered",
    "normalize_event_badge_color",
    "refund_transaction",
    "register_event_stock_adjustment",
    "register_event_stock_entry",
    "register_event_stock_exit",
    "register_stock_adjustment",
    "register_stock_entry",
    "register_stock_exit",
    "remove_product_from_event",
    "replace_seller_event_assignment",
    "reset_totem_to_default_state",
    "restore_event",
    "set_product_active",
    "sync_products_from_wake",
    "upsert_wake_variant",
    "update_event",
    "update_event_product_stock",
    "update_pending_transaction",
    "update_product_min_stock",
    "update_seller_account",
    "update_seller_last_login",
]

